# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    pipebot_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

pipebot_controller:
  ros__parameters:
    joints:
      - rot_1
      - rot_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity