controller_mananger:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    Arm_Controller:
      type: joint_trajectory_controller/JointTrajectoryController

Arm_Controller:
  ros__parameters:
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_4

    allow_partial_joints_goal: true
